### ISSUE TITLE
Strokes are twice as wide as other renderers

### ISSUE THREAD

**Issue by whereswaldon** [inkeliz/giosvg#6]
![Home](https://user-images.githubusercontent.com/3922125/187710224-de98ac3a-9dfe-4fac-ad57-f13fdd947513.svg)
![Home](https://user-images.githubusercontent.com/3922125/187710232-414b5547-0f14-4f08-b459-2c5a71d9d81d.png)

Here is an SVG and the inkscape 16x16px rendering of it. When rendered via `giosvg`, I get this result:
![out](https://user-images.githubusercontent.com/3922125/187736780-72e4fc3b-8c5e-479e-a518-1b7e7d8dfdb7.png)

Here's a simple program to render it:

```go
package main

import (
	_ "embed"
	"image"
	"image/color"
	"image/png"
	"os"

	"gioui.org/gpu/headless"
	"gioui.org/layout"
	"gioui.org/op"
	"gioui.org/op/paint"
	"gioui.org/unit"
	"github.com/inkeliz/giosvg"
)

//go:embed Home.svg
var data []byte

func main() {
	v, err := giosvg.NewVector(data)
	if err != nil {
		panic(err)
	}
	size := image.Point{
		X: 16,
		Y: 16,
	}
	w, err := headless.NewWindow(size.X, size.Y)
	if err != nil {
		panic(err)
	}
	i := giosvg.NewIcon(v)
	var ops op.Ops
	gtx := layout.Context{
		Constraints: layout.Exact(size),
		Metric: unit.Metric{
			PxPerDp: 1,
			PxPerSp: 1,
		},
		Queue: nil,
		Ops:   &ops,
	}
	paint.ColorOp{Color: color.NRGBA{A: 255}}.Add(gtx.Ops)
	i.Layout(gtx)
	if err := w.Frame(gtx.Ops); err != nil {
		panic(err)
	}

	img := image.NewRGBA(image.Rectangle{
		Max: size,
	})
	if err := w.Screenshot(img); err != nil {
		panic(err)
	}
	f, err := os.Create("out.png")
	if err != nil {
		panic(err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			panic(err)
		}
	}()
	if err := png.Encode(f, img); err != nil {
		panic(err)
	}
}
```

I get the results I expect by applying this patch to `giosvg`:

```diff
diff --git a/internal/svgparser/draw.go b/internal/svgparser/draw.go
index 8fef057..36c07c8 100644
--- a/internal/svgparser/draw.go
+++ b/internal/svgparser/draw.go
@@ -172,7 +172,7 @@ type StrokeOptions struct {
 var DefaultStyle = PathStyle{
 	FillOpacity:       1.0,
 	LineOpacity:       1.0,
-	LineWidth:         2.0,
+	LineWidth:         1.0,
 	UseNonZeroWinding: true,
 	Join: JoinOptions{
 		MiterLimit:   4,
@@ -234,7 +234,7 @@ func (svgp *SvgPath) drawTransformed(d Driver, opacity float64, t Matrix2D) {
 			leadLineCap = svgp.Style.Join.LeadLineCap
 		}
 		stroker.SetStrokeOptions(StrokeOptions{
-			LineWidth: float32(svgp.Style.LineWidth),
+			LineWidth: float32(svgp.Style.LineWidth) / 2,
 			Join: JoinOptions{
 				MiterLimit:   svgp.Style.Join.MiterLimit,
 				LineJoin:     svgp.Style.Join.LineJoin,
```

Am I doing something wrong?

**Comment by inkeliz** [comment]
I think it was suppose to modify the `DefaultStyle`, but it's now living in `/internal`. 💩

If you set `stroke-width="1"` in the SVG the issue persists? I don't understand why you need `LineWidth: float32(svgp.Style.LineWidth) / 2` at same time. The `stroke-width` will override the default. _I think it makes more sense to set to `1` instead of `2` anyway._

-------------

Maybe that related to:

https://github.com/inkeliz/giosvg/blob/5eaaf2e77e84b2e975d4b1324729f745622c1263/internal/svgdraw/svgdraw.go#L130-L132

**Comment by inkeliz** [comment]
See if #7 fixes the issue:

```patch
From 38253c72da44af0bb2829e36f284acfe88690ee8 Mon Sep 17 00:00:00 2001
From: Inkeliz <inkeliz@inkeliz.com>
Date: Wed, 31 Aug 2022 19:14:06 +0100
Subject: [PATCH] fix: stroke scaling calculation

Before this change, the stroke was wrongly calculated.

Fixes #6
---
 giosvg.go                  | 2 +-
 internal/svgparser/draw.go | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/giosvg.go b/giosvg.go
index f5018b9..cf4308c 100644
--- a/giosvg.go
+++ b/giosvg.go
@@ -65,7 +65,7 @@ func NewVectorReader(reader io.Reader) (Vector, error) {
 		}
 
 		render.SetTarget(0-render.ViewBox.X, 0-render.ViewBox.Y, float64(w), float64(h))
-		scale := float32(float64(w)/render.ViewBox.W) + float32(float64(h)/render.ViewBox.H)/2
+		scale := float32(float32(float64(w)/render.ViewBox.W)+float32(float64(h)/render.ViewBox.H)) / 2
 		render.Draw(&svgdraw.Driver{Ops: ops, Scale: scale}, 1.0)
 
 		return layout.Dimensions{Size: image.Point{X: int(w), Y: int(h)}}
diff --git a/internal/svgparser/draw.go b/internal/svgparser/draw.go
index 8fef057..5b95dd1 100644
--- a/internal/svgparser/draw.go
+++ b/internal/svgparser/draw.go
@@ -172,7 +172,7 @@ type StrokeOptions struct {
 var DefaultStyle = PathStyle{
 	FillOpacity:       1.0,
 	LineOpacity:       1.0,
-	LineWidth:         2.0,
+	LineWidth:         1.0,
 	UseNonZeroWinding: true,
 	Join: JoinOptions{
 		MiterLimit:   4,
```

https://github.com/inkeliz/giosvg/commit/38253c72da44af0bb2829e36f284acfe88690ee8.patch

**Comment by JackMordaunt** [comment]
Hi @inkeliz, I've collected some samples for this patch. I think this is pretty good. @whereswaldon what do you think? 

original:
![Home-inkscape](https://user-images.githubusercontent.com/6916093/187809576-c318cf7d-8bb5-4da5-b1e6-eef817a4b2f0.svg)

giosvg -> png:
![Home-giosvg](https://user-images.githubusercontent.com/6916093/187808492-dfa5a8ff-dc46-41b8-85ed-3d2277ba415b.png) 16px
![out](https://user-images.githubusercontent.com/6916093/187809376-ef9e9d56-363a-4acd-8ff2-1981b16e3e3c.png) 18px


inkscape -> png:
![Home-inkscape](https://user-images.githubusercontent.com/6916093/187809443-49842309-ec0f-4ee2-812e-5b002d8dfbfc.png) 96dpi
![Home-inkscape-108dpi](https://user-images.githubusercontent.com/6916093/187809503-d4e17fff-82bc-4d98-8c5a-79ba70d5aa1b.png) 108dpi

in-app result:

![image](https://user-images.githubusercontent.com/6916093/187809755-1f0703b1-32e9-40ab-8c95-a26364ddb5df.png)

**Comment by whereswaldon** [comment]
@inkeliz Nice work! `giosvg` now renders consistently with Inkscape. I think the default stroke width was part of the issue, but the scale calculation bug was the real culprit. I was just working around that by halving the stroke width at render time.

Inkscape: 
![Home](https://user-images.githubusercontent.com/3922125/187939356-5ae0c0a7-e216-4577-b14c-5c2393c600bc.png)


`giosvg`:
![out](https://user-images.githubusercontent.com/3922125/187939321-aa406bca-6d67-4923-b61f-18c81f5e11d2.png)
