### ISSUE TITLE
panic in svggen

### ISSUE THREAD

**Issue by fasmide** [inkeliz/giosvg#9]
Hello

When trying to convert the school-bus.svg into vector, the tool crashes and doesn't give any impression on what's wrong - I don't think it's the input file as I've tried a lot simpler svg's as well:

```
$ ~/go/bin/svggen -i school-bus.svg -o bus-vector.go
panic: 1:12: expected ';', found '-'

goroutine 1 [running]:
main.main()
        /home/fas/go/pkg/mod/github.com/inkeliz/giosvg@v0.0.0-20220907230924-ba74fc8e323f/cmd/svggen/main.go:206 +0xa0d

```

**Comment by inkeliz** [comment]
I can't reproduce that problem, on macOS:

```bash
git clone git@github.com:inkeliz/giosvg.git

cd giosvg/example

rm -f school-bus.go

go run github.com/inkeliz/giosvg/cmd/svggen -i "school-bus.svg" -o "bus-vector.go" -pkg "main"
```

To test the result:

```
go run main.go bus-vector.go
```

Works fine. 🧐

**Comment by inkeliz** [comment]
The issue seems to be related to Golang Formatter:

https://github.com/inkeliz/giosvg/blob/ba74fc8e323f05bcb9244f33fcea026bd343abc7/cmd/svggen/main.go#L204-L208

Maybe you can modify that file to:

```
save.Write(out.Bytes())
```

That will save the broken Golang code into the file, so you can take a look why it's not been properly generated.

**Comment by inkeliz** [comment]
Try to add `-pkg`, so you can set the name of the package. Maybe your folder contains some invalid name for package:

```
~/go/bin/svggen -i school-bus.svg -o bus-vector.go          -pkg something
```

**Comment by fasmide** [comment]
Thanks a lot for looking into the issue :)

> Try to add `-pkg`, so you can set the name of the package. Maybe your folder contains some invalid name for package:

I didn't realize it had a `-pkg` flag; I used the sample from the https://github.com/inkeliz/giosvg/blob/master/README.md?plain=1#L47 

So while it seems like a good idea to check for package names with spaces, I think my issue was that the package name is empty

**Comment by inkeliz** [comment]
In that case the folder name will be used as pkg. So, if the output folder is `/foo bar/vector.go`, `pkg` would be `foo bar`. In most case the name of the folder is the name of package, in Golang.
